RustboroCity_House4_MapScripts::
	.byte 0

RustboroCity_House4_EventScript_Woman::
	msgbox RustboroCity_Flat3_2F_Text_Woman, MSGBOX_NPC
	end

RustboroCity_Flat3_2F_Text_Woman:
	.string "Me and my husband make an effort to\n"
	.string "visit the museum at least once a year.$"

RustboroCity_House4_EventScript_Hiker::
	msgbox RustboroCity_Flat3_2F_Text_Museum, MSGBOX_NPC
	end

RustboroCity_Flat3_2F_Text_Museum:
	.string "Have you visited the Devon Museum?\n"
	.string "They have fossils of ancient Pokémon.$"
