#ifndef GUARD_CONSTANTS_FIELD_BURN_H
#define GUARD_CONSTANTS_FIELD_BURN_H

#define FLDBRN_NONE  0
#define FLDBRN_BRN   1
#define FLDBRN_FNT   2

#define FLDBRN_NO_WHITEOUT        0
#define FLDBRN_WHITEOUT           1
#define FLDBRN_FRONTIER_WHITEOUT  2

#endif //GUARD_CONSTANTS_FIELD_BURN_H
