#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FLASH) \
    F(CUT) \
    F(ROCK_SMASH) \
    F(HEADBUTT) \
    F(TELEPORT) \
    F(SECRET_POWER) \
    F(CHARGE_BEAM) \
    F(DEFOG) \
    F(WATERFALL) \
    F(WHIRLPOOL) \
    F(SUNNY_DAY) \
    F(RAIN_DANCE) \
    F(SANDSTORM) \
    F(HAIL) \
    F(ROAR) \
    F(PROTECT) \
    F(LIGHT_SCREEN) \
    F(REFLECT) \
    F(SAFEGUARD) \
    F(TAUNT) \
    F(TORMENT) \
    F(EMBARGO) \
    F(THIEF) \
    F(ATTRACT) \
    F(SKILL_SWAP) \
    F(TRICK_ROOM) \
    F(SUBSTITUTE) \
    F(REST) \
    F(NATURE_POWER) \
    F(HIDDEN_POWER) \
    F(FALSE_SWIPE) \
    F(RETURN) \
    F(SLEEP_TALK) \
    F(DREAM_EATER) \
    F(SWAGGER) \
    F(TOXIC) \
    F(WILL_O_WISP) \
    F(THUNDER_WAVE) \
    F(HONE_CLAWS) \
    F(AERIAL_ACE) \
    F(VENOSHOCK) \
    F(ROCK_TOMB) \
    F(INFESTATION) \
    F(STEEL_WING) \
    F(PSYCHIC) \
    F(PAYBACK) \
    F(DRAGON_CLAW) \
    F(DRAGON_TAIL) \
    F(INCINERATE) \
    F(FROST_BREATH) \
    F(DRAINING_KISS) \
    F(SCALD) \
    F(BULLDOZE) \
    F(BRICK_BREAK) \
    F(FACADE) \
    F(DOUBLE_TEAM) \
    F(SWORDS_DANCE) \
    F(CALM_MIND) \
    F(PSYCH_UP) \
    F(BULK_UP) \
    F(ROOST) \
    F(ROCK_POLISH) \
    F(FIRE_FANG) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(SLUDGE_BOMB) \
    F(MAGICAL_LEAF) \
    F(SMACK_DOWN) \
    F(U_TURN) \
    F(VOLT_SWITCH) \
    F(OVERHEAT) \
    F(GYRO_BALL) \
    F(GRASS_KNOT) \
    F(FLAMETHROWER) \
    F(THUNDERBOLT) \
    F(ICE_BEAM) \
    F(HYPER_BEAM) \
    F(GIGA_IMPACT) \
    F(PHANTOM_FORCE) \
    F(SOLAR_BEAM) \
    F(EXPLOSION) \
    F(EARTHQUAKE) \
    F(FIRE_BLAST) \
    F(THUNDER) \
    F(BLIZZARD) \
    F(FOCUS_PUNCH) \
    F(STONE_EDGE) \
    F(PSYSHOCK) \
    F(DAZZLING_GLEAM) \
    F(POISON_JAB) \
    F(GIGA_DRAIN) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(SHADOW_CLAW) \
    F(SHADOW_BALL) \
    F(IRON_TAIL) \
    F(FLASH_CANNON) \
    F(ENERGY_BALL) \
    F(FLING) \
    F(DARK_PULSE)

#define FOREACH_HM(F) \
    F(SURF) \
    F(STRENGTH) \
    F(FLY) \
    F(DIVE) \
    F(SEA_STRIDE) \
    F(DIG) \
    F(LAVA_PLUME) \
    F(ROCK_CLIMB) \
    F(MUDDY_WATER) \
    F(TELEKINESIS) \
    F(BODY_PRESS) \
    F(ACROBATICS) \
    F(SLUDGE_WAVE) \
    F(DRAGON_ASCENT) 

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
