gText_WantToUseSurf::
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to{COLOR DYNAMIC_COLOR5} Surf{COLOR DARK_GRAY}?$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1} used{COLOR DYNAMIC_COLOR5} Surf{COLOR DARK_GRAY}!$"

gText_PlayerUsedSeaStride::
	.string "{STR_VAR_1} used{COLOR DYNAMIC_COLOR5} Sea Stride{COLOR DARK_GRAY}!$"

gText_PlayerUsedMuddyWater::
	.string "{STR_VAR_1} used{COLOR DYNAMIC_COLOR5} Muddy Water{COLOR DARK_GRAY}!$"
