name: 🙏 Feature Request 🙏
description: Do you want a feature for the Expansion? Let me know!
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all required fields with as many details as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe what you want to be done.
        Attach images/videos if possible.
      placeholder: |
        Please enter a description of the feature. Here you can also attach log screenshots, gifs or a video
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Discord contact info
      description: Provide your Discord tag here so I can contact you in case we need more details. If you have DMs closed I won't be able to contact you as well.
      placeholder: ex. ghoulmage
    validations:
      required: false
