RustboroCity_Flat3_1F_MapScripts::
	.byte 0

RustboroCity_Flat3_1F_EventScript_Man::
	msgbox RustboroCity_Flat3_1F_Text_TrainerSchool, MSGBOX_NPC
	end

RustboroCity_Flat3_1F_Text_TrainerSchool:
	.string "To take on the League, you'll have\n"
	.string "to graduate from the Trainer School.$"

RustboroCity_Flat3_1F_EventScript_Researcher::
	msgbox RustboroCity_Flat3_1F_Text_DevonSchool, MSGBOX_NPC
	end

RustboroCity_Flat3_1F_Text_DevonSchool:
	.string "The Devon corporation funds a lot\n"
	.string "of pokémon research projects.\p"
	.string "But they are also a primary funder.\n"
	.string "of the Pokémon league.$"
