#ifndef GUARD_FISHING_GAME_TREASURES_H
#define GUARD_FISHING_GAME_TREASURES_H

#include "item.h"
#include "constants/items.h"

static const u16 sTreasureItems[] =
{
    // Common
    ITEM_POTION,
    ITEM_POKE_BALL,
    ITEM_ANTIDOTE,
    ITEM_X_ATTACK,
    ITEM_X_DEFEND,
    ITEM_REPEL,
    ITEM_ESCAPE_ROPE,
    ITEM_POKE_DOLL,
    ITEM_FULL_HEAL,
    ITEM_STARDUST,

    // Uncommon
    ITEM_SUPER_POTION,
    ITEM_GREAT_BALL,
    ITEM_REVIVE,
    ITEM_SUPER_REPEL,
    ITEM_ETHER,
    ITEM_PROTEIN,
    ITEM_HP_UP,
    ITEM_MAX_ELIXIR,
    ITEM_NUGGET,
    ITEM_HEART_SCALE,

    // Rare
    ITEM_HYPER_POTION,
    ITEM_ULTRA_BALL,
    ITEM_FULL_RESTORE,
    ITEM_MAX_REPEL,
    ITEM_MAX_REVIVE,
    ITEM_ELIXIR,
    ITEM_RARE_CANDY,
    ITEM_KINGS_ROCK,
    ITEM_LEFTOVERS,
    ITEM_TM_EARTHQUAKE,
};

#endif // GUARD_FISHING_GAME_TREASURES_H
